name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  load-testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Build
        run: npm run build

      - name: Install Artillery
        run: npm install -g artillery

      - name: Start backend server
        run: nohup npm run backend &

      - name: Run Playwright test with Artillery
        run: artillery run e2e/test-1.spec.ts

      - name: Save load test report
        run: artillery run --output report.json load-tests/basic.yml

      - name: Upload load test report
        uses: actions/upload-artifact@v3
        with:
          name: load-test-report
          path: report.json